/**
 * Ashen Road - Game Constants & Database Definitions
 */
import { Item, NPC, Quest, GunConfig, RespawnLocation } from '../types';

export const WORLD_WIDTH = 3000;
export const WORLD_HEIGHT = 2000;
export const WORLD_SEED = 74291;

export const PLAYER_BASE_SPEED = 180;
export const PLAYER_SPRINT_SPEED = 270;
export const SPRINT_STAMINA_COST = 15; // per second
export const ATTACK_STAMINA_COST = 20;
export const ATTACK_COOLDOWN = 0.45; // seconds
export const ATTACK_RANGE = 65;
export const ATTACK_ARC_DEG = 100;
export const STAMINA_REGEN_RATE = 20; // per second
export const STAMINA_REGEN_DELAY = 1.0; // delay after attack before regen
export const INTERACTION_RANGE = 70;

// Tactical Dash / Dodge Roll
export const DASH_SPEED = 560;
export const DASH_DURATION = 0.24;
export const DASH_COOLDOWN = 0.75;
export const DASH_STAMINA_COST = 22;

export const DAY_NIGHT_FULL_CYCLE = 600; // 10 minutes in seconds

// Infinite World Chunk Parameters
export const CHUNK_SIZE = 800;
export const CHUNK_LOAD_RADIUS = 2; // load 5x5 chunks around player

export const GUN_CONFIGS: Record<string, GunConfig> = {
  glock: {
    id: 'glock',
    name: 'Glock-19 Tactical',
    category: 'Pistol',
    damage: 24,
    fireRate: 4.8,
    magSize: 15,
    currentMag: 15,
    reserveAmmo: 120,
    maxReserveAmmo: 240,
    reloadTime: 1.1,
    bulletSpeed: 720,
    bulletCount: 1,
    spread: 0.035,
    recoil: 2.2,
    knockback: 10,
    range: 580,
    isAuto: false,
    penetration: 1,
    splashRadius: 0,
    color: '#fef08a',
    description: 'Crisp 9mm semi-auto sidearm with fast handling and pinpoint accuracy.',
    value: 50,
  },
  shotgun: {
    id: 'shotgun',
    name: 'SPAS-12 Trench Shotgun',
    category: 'Shotgun',
    damage: 18, // x7 pellets = 126 max damage
    fireRate: 1.25,
    magSize: 8,
    currentMag: 8,
    reserveAmmo: 48,
    maxReserveAmmo: 96,
    reloadTime: 1.7,
    bulletSpeed: 560,
    bulletCount: 7,
    spread: 0.24,
    recoil: 8.5,
    knockback: 35,
    range: 400,
    isAuto: false,
    penetration: 1,
    splashRadius: 0,
    color: '#fb923c',
    description: 'Devastating pump-action shotgun firing 7-pellet buckshot cones.',
    value: 140,
  },
  ak47: {
    id: 'ak47',
    name: 'AK-47 Assault Rifle',
    category: 'Assault Rifle',
    damage: 32,
    fireRate: 8.5,
    magSize: 30,
    currentMag: 30,
    reserveAmmo: 180,
    maxReserveAmmo: 360,
    reloadTime: 1.55,
    bulletSpeed: 780,
    bulletCount: 1,
    spread: 0.06,
    recoil: 4.2,
    knockback: 14,
    range: 720,
    isAuto: true,
    penetration: 1,
    splashRadius: 0,
    color: '#fdba74',
    description: 'Iconic select-fire assault rifle with high stopping power.',
    value: 240,
  },
  sniper: {
    id: 'sniper',
    name: 'AWM .50 Heavy Sniper',
    category: 'Sniper Rifle',
    damage: 165,
    fireRate: 0.85,
    magSize: 5,
    currentMag: 5,
    reserveAmmo: 25,
    maxReserveAmmo: 50,
    reloadTime: 2.1,
    bulletSpeed: 1200,
    bulletCount: 1,
    spread: 0.005,
    recoil: 11.5,
    knockback: 42,
    range: 1150,
    isAuto: false,
    penetration: 4, // Pierces up to 4 enemies in a straight line
    splashRadius: 0,
    color: '#38bdf8',
    description: 'Bolt-action anti-materiel sniper rifle that pierces through multiple enemies.',
    value: 360,
  },
  smg: {
    id: 'smg',
    name: 'MP5 Tactical SMG',
    category: 'SMG',
    damage: 17,
    fireRate: 13.5,
    magSize: 40,
    currentMag: 40,
    reserveAmmo: 240,
    maxReserveAmmo: 480,
    reloadTime: 1.25,
    bulletSpeed: 660,
    bulletCount: 1,
    spread: 0.085,
    recoil: 2.2,
    knockback: 7,
    range: 520,
    isAuto: true,
    penetration: 1,
    splashRadius: 0,
    color: '#facc15',
    description: 'High-cyclic submachine gun built for agility and bullet hose suppression.',
    value: 175,
  },
  rpg: {
    id: 'rpg',
    name: 'RPG-7 Rocket Launcher',
    category: 'Heavy Explosive',
    damage: 260,
    fireRate: 0.55,
    magSize: 1,
    currentMag: 1,
    reserveAmmo: 8,
    maxReserveAmmo: 20,
    reloadTime: 2.4,
    bulletSpeed: 420,
    bulletCount: 1,
    spread: 0.02,
    recoil: 14.0,
    knockback: 70,
    range: 750,
    isAuto: false,
    penetration: 1,
    splashRadius: 105,
    isRocket: true,
    color: '#ef4444',
    description: 'Fires high-explosive rockets that detonate in devastating shockwaves.',
    value: 480,
  },
  plasma: {
    id: 'plasma',
    name: 'Plasma Blaster',
    category: 'Energy Weapon',
    damage: 52,
    fireRate: 5.8,
    magSize: 25,
    currentMag: 25,
    reserveAmmo: 150,
    maxReserveAmmo: 300,
    reloadTime: 1.35,
    bulletSpeed: 840,
    bulletCount: 1,
    spread: 0.03,
    recoil: 2.8,
    knockback: 18,
    range: 680,
    isAuto: true,
    penetration: 2,
    splashRadius: 35,
    isLaser: true,
    color: '#a855f7',
    description: 'Direct-energy rifle discharging superheated plasma bolts.',
    value: 420,
  },
  tesla: {
    id: 'tesla',
    name: 'Tesla Arc Cannon',
    category: 'Energy',
    damage: 44,
    fireRate: 4.2,
    magSize: 24,
    currentMag: 24,
    reserveAmmo: 144,
    maxReserveAmmo: 288,
    reloadTime: 1.35,
    bulletSpeed: 950,
    bulletCount: 1,
    spread: 0.04,
    recoil: 2.4,
    knockback: 16,
    range: 640,
    isAuto: true,
    penetration: 3,
    splashRadius: 65,
    isTesla: true,
    isLaser: true,
    color: '#38bdf8',
    description: 'Discharges chaining high-voltage electric arcs leaping between hostile targets.',
    value: 550,
  },
  flamethrower: {
    id: 'flamethrower',
    name: 'Vulcan Pyrocaster',
    category: 'Heavy Assault',
    damage: 18,
    fireRate: 18,
    magSize: 90,
    currentMag: 90,
    reserveAmmo: 360,
    maxReserveAmmo: 720,
    reloadTime: 1.85,
    bulletSpeed: 440,
    bulletCount: 2,
    spread: 0.24,
    recoil: 1.4,
    knockback: 6,
    range: 390,
    isAuto: true,
    penetration: 4,
    splashRadius: 28,
    isFlamethrower: true,
    color: '#f97316',
    description: 'Unleashes a roaring cone of incendiary napalm particles engulfing swarms.',
    value: 520,
  },
  minigun: {
    id: 'minigun',
    name: 'Titan-6 Heavy Minigun',
    category: 'Heavy Assault',
    damage: 28,
    fireRate: 20,
    magSize: 150,
    currentMag: 150,
    reserveAmmo: 600,
    maxReserveAmmo: 1200,
    reloadTime: 2.8,
    bulletSpeed: 820,
    bulletCount: 1,
    spread: 0.12,
    recoil: 3.8,
    knockback: 14,
    range: 640,
    isAuto: true,
    penetration: 1,
    splashRadius: 0,
    color: '#f59e0b',
    description: 'Six-barrel rotary vulcan delivering unmatched sustained suppressive fire.',
    value: 750,
  },
  cryo: {
    id: 'cryo',
    name: 'Cryo Freeze Ray',
    category: 'Energy',
    damage: 32,
    fireRate: 6.8,
    magSize: 36,
    currentMag: 36,
    reserveAmmo: 180,
    maxReserveAmmo: 360,
    reloadTime: 1.45,
    bulletSpeed: 720,
    bulletCount: 1,
    spread: 0.04,
    recoil: 1.8,
    knockback: 8,
    range: 580,
    isAuto: true,
    penetration: 2,
    splashRadius: 32,
    isCryo: true,
    color: '#67e8f9',
    description: 'Projects subzero cryo-photons chilling targets and immobilizing them.',
    value: 490,
  },
  railgun: {
    id: 'railgun',
    name: 'Hyperion Quantum Railgun',
    category: 'Sniper Rifle',
    damage: 380,
    fireRate: 0.65,
    magSize: 3,
    currentMag: 3,
    reserveAmmo: 18,
    maxReserveAmmo: 36,
    reloadTime: 2.4,
    bulletSpeed: 1600,
    bulletCount: 1,
    spread: 0.001,
    recoil: 16.0,
    knockback: 80,
    range: 1300,
    isAuto: false,
    penetration: 8,
    splashRadius: 40,
    isRailgun: true,
    color: '#ec4899',
    description: 'Hyper-velocity electromagnetic kinetic accelerator punching through all obstacles.',
    value: 880,
  },
  cluster_missile: {
    id: 'cluster_missile',
    name: 'Hydra Cluster Pod',
    category: 'Heavy Explosive',
    damage: 95,
    fireRate: 1.25,
    magSize: 4,
    currentMag: 4,
    reserveAmmo: 24,
    maxReserveAmmo: 48,
    reloadTime: 2.2,
    bulletSpeed: 480,
    bulletCount: 4,
    spread: 0.35,
    recoil: 10.0,
    knockback: 45,
    range: 750,
    isAuto: false,
    penetration: 1,
    splashRadius: 75,
    isCluster: true,
    isRocket: true,
    color: '#ef4444',
    description: 'Launches salvos of 4 smart-seeking micro-missiles blanketing target areas.',
    value: 820,
  },
  sawblade: {
    id: 'sawblade',
    name: 'Ripper Sawblade Cannon',
    category: 'Special',
    damage: 75,
    fireRate: 2.5,
    magSize: 12,
    currentMag: 12,
    reserveAmmo: 60,
    maxReserveAmmo: 120,
    reloadTime: 1.6,
    bulletSpeed: 580,
    bulletCount: 1,
    spread: 0.06,
    recoil: 5.0,
    knockback: 30,
    range: 620,
    isAuto: true,
    penetration: 4,
    splashRadius: 0,
    isSawblade: true,
    color: '#10b981',
    description: 'Launches spinning hardened alloy buzzsaw disks that ricochet and slice targets.',
    value: 620,
  },
  orbital_strike: {
    id: 'orbital_strike',
    name: 'Aegis Orbital Beacon',
    category: 'Superweapon',
    damage: 600,
    fireRate: 0.35,
    magSize: 1,
    currentMag: 1,
    reserveAmmo: 6,
    maxReserveAmmo: 12,
    reloadTime: 3.2,
    bulletSpeed: 800,
    bulletCount: 1,
    spread: 0.01,
    recoil: 20.0,
    knockback: 100,
    range: 950,
    isAuto: false,
    penetration: 1,
    splashRadius: 180,
    isOrbital: true,
    color: '#a855f7',
    description: 'Designates target coordinates for orbital particle beam saturation.',
    value: 1250,
  },
};

export const INITIAL_GUN_ARSENAL: GunConfig[] = [
  { ...GUN_CONFIGS.glock },
  { ...GUN_CONFIGS.shotgun },
  { ...GUN_CONFIGS.ak47 },
  { ...GUN_CONFIGS.sniper },
  { ...GUN_CONFIGS.smg },
  { ...GUN_CONFIGS.rpg },
  { ...GUN_CONFIGS.plasma },
  { ...GUN_CONFIGS.tesla },
  { ...GUN_CONFIGS.flamethrower },
  { ...GUN_CONFIGS.minigun },
  { ...GUN_CONFIGS.cryo },
  { ...GUN_CONFIGS.railgun },
  { ...GUN_CONFIGS.cluster_missile },
  { ...GUN_CONFIGS.sawblade },
  { ...GUN_CONFIGS.orbital_strike },
];

export const ITEMS: Record<string, Item> = {
  // Guns
  glock_gun: {
    id: 'glock_gun',
    name: 'Glock-19 Tactical',
    type: 'GUN',
    description: 'Crisp 9mm semi-auto sidearm with fast handling and pinpoint accuracy.',
    stackable: false,
    quantity: 1,
    value: 50,
    damage: 24,
    gunConfig: { ...GUN_CONFIGS.glock },
  },
  shotgun_gun: {
    id: 'shotgun_gun',
    name: 'SPAS-12 Trench Shotgun',
    type: 'GUN',
    description: 'Devastating pump-action shotgun firing 7-pellet buckshot cones.',
    stackable: false,
    quantity: 1,
    value: 140,
    damage: 18,
    gunConfig: { ...GUN_CONFIGS.shotgun },
  },
  ak47_gun: {
    id: 'ak47_gun',
    name: 'AK-47 Assault Rifle',
    type: 'GUN',
    description: 'Iconic select-fire assault rifle with high stopping power.',
    stackable: false,
    quantity: 1,
    value: 240,
    damage: 32,
    gunConfig: { ...GUN_CONFIGS.ak47 },
  },
  sniper_gun: {
    id: 'sniper_gun',
    name: 'AWM .50 Heavy Sniper',
    type: 'GUN',
    description: 'Bolt-action anti-materiel sniper rifle that pierces through multiple enemies.',
    stackable: false,
    quantity: 1,
    value: 360,
    damage: 165,
    gunConfig: { ...GUN_CONFIGS.sniper },
  },
  smg_gun: {
    id: 'smg_gun',
    name: 'MP5 Tactical SMG',
    type: 'GUN',
    description: 'High-cyclic submachine gun built for agility and bullet hose suppression.',
    stackable: false,
    quantity: 1,
    value: 500,
    damage: 500,
    gunConfig: { ...GUN_CONFIGS.smg },
  },
  rpg_gun: {
    id: 'rpg_gun',
    name: 'RPG-7 Rocket Launcher',
    type: 'GUN',
    description: 'Fires high-explosive rockets that detonate in devastating shockwaves.',
    stackable: false,
    quantity: 1,
    value: 480,
    damage: 260,
    gunConfig: { ...GUN_CONFIGS.rpg },
  },
  plasma_gun: {
    id: 'plasma_gun',
    name: 'Plasma Blaster',
    type: 'GUN',
    description: 'Direct-energy rifle discharging superheated plasma bolts.',
    stackable: false,
    quantity: 1,
    value: 420,
    damage: 52,
    gunConfig: { ...GUN_CONFIGS.plasma },
  },
  tesla_gun: {
    id: 'tesla_gun',
    name: 'Tesla Arc Cannon',
    type: 'GUN',
    description: 'Discharges chaining high-voltage electric arcs leaping between hostile targets.',
    stackable: false,
    quantity: 1,
    value: 550,
    damage: 44,
    gunConfig: { ...GUN_CONFIGS.tesla },
  },
  flamethrower_gun: {
    id: 'flamethrower_gun',
    name: 'Vulcan Pyrocaster',
    type: 'GUN',
    description: 'Unleashes a roaring cone of incendiary napalm particles engulfing swarms.',
    stackable: false,
    quantity: 1,
    value: 520,
    damage: 18,
    gunConfig: { ...GUN_CONFIGS.flamethrower },
  },
  minigun_gun: {
    id: 'minigun_gun',
    name: 'Titan-6 Heavy Minigun',
    type: 'GUN',
    description: 'Six-barrel rotary vulcan delivering unmatched sustained suppressive fire.',
    stackable: false,
    quantity: 1,
    value: 750,
    damage: 28,
    gunConfig: { ...GUN_CONFIGS.minigun },
  },
  cryo_gun: {
    id: 'cryo_gun',
    name: 'Cryo Freeze Ray',
    type: 'GUN',
    description: 'Projects subzero cryo-photons chilling targets and immobilizing them.',
    stackable: false,
    quantity: 1,
    value: 490,
    damage: 32,
    gunConfig: { ...GUN_CONFIGS.cryo },
  },
  railgun_gun: {
    id: 'railgun_gun',
    name: 'Hyperion Quantum Railgun',
    type: 'GUN',
    description: 'Hyper-velocity electromagnetic kinetic accelerator punching through all obstacles.',
    stackable: false,
    quantity: 1,
    value: 880,
    damage: 380,
    gunConfig: { ...GUN_CONFIGS.railgun },
  },
  cluster_missile_gun: {
    id: 'cluster_missile_gun',
    name: 'Hydra Cluster Pod',
    type: 'GUN',
    description: 'Launches salvos of 4 smart-seeking micro-missiles blanketing target areas.',
    stackable: false,
    quantity: 1,
    value: 820,
    damage: 95,
    gunConfig: { ...GUN_CONFIGS.cluster_missile },
  },
  sawblade_gun: {
    id: 'sawblade_gun',
    name: 'Ripper Sawblade Cannon',
    type: 'GUN',
    description: 'Launches spinning hardened alloy buzzsaw disks that ricochet and slice targets.',
    stackable: false,
    quantity: 1,
    value: 620,
    damage: 75,
    gunConfig: { ...GUN_CONFIGS.sawblade },
  },
  orbital_strike_gun: {
    id: 'orbital_strike_gun',
    name: 'Aegis Orbital Beacon',
    type: 'GUN',
    description: 'Designates target coordinates for orbital particle beam saturation.',
    stackable: false,
    quantity: 1,
    value: 1250,
    damage: 600,
    gunConfig: { ...GUN_CONFIGS.orbital_strike },
  },

  // Colony & Crafting Materials
  raw_ore: {
    id: 'raw_ore',
    name: 'Refined Iron Ore',
    type: 'MATERIAL',
    description: 'Mined mineral ore used for base structures and ammunition fabrication.',
    stackable: true,
    quantity: 1,
    value: 10,
  },
  titanium_alloy: {
    id: 'titanium_alloy',
    name: 'Titanium Ingot',
    type: 'MATERIAL',
    description: 'Hardened aerospace-grade titanium used for defense turrets and heavy armor.',
    stackable: true,
    quantity: 1,
    value: 25,
  },
  energy_cell: {
    id: 'energy_cell',
    name: 'High-Density Energy Cell',
    type: 'MATERIAL',
    description: 'Charged battery core powering laser weapons, shield domes, and vehicles.',
    stackable: true,
    quantity: 1,
    value: 40,
  },
  cyber_deck: {
    id: 'cyber_deck',
    name: 'Omni-Hack Cyber-Deck',
    type: 'TOOL',
    description: 'Military intrusion console that overclocks machinery and hacks hostile mechs to fight for you.',
    stackable: false,
    quantity: 1,
    value: 300,
  },

  // Ammo Cache & Supplies
  ammo_cache: {
    id: 'ammo_cache',
    name: 'Military Ammo Cache',
    type: 'CONSUMABLE',
    description: 'Heavy military ammo crate. Refills magazines and reserves for all weapons!',
    stackable: true,
    quantity: 1,
    value: 25,
  },

  // Melee & Classic
  rusty_sword: {
    id: 'rusty_sword',
    name: 'Rusty Sword',
    type: 'WEAPON',
    description: 'An old, chipped blade. Better than bare fists.',
    stackable: false,
    quantity: 1,
    value: 10,
    damage: 5,
  },
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    type: 'WEAPON',
    description: 'A finely balanced blade forged from sturdy iron.',
    stackable: false,
    quantity: 1,
    value: 50,
    damage: 12,
  },
  steel_sword: {
    id: 'steel_sword',
    name: 'Steel Sword',
    type: 'WEAPON',
    description: 'A razor-sharp masterwork steel sword.',
    stackable: false,
    quantity: 1,
    value: 150,
    damage: 22,
  },
  cloth_tunic: {
    id: 'cloth_tunic',
    name: 'Cloth Tunic',
    type: 'ARMOR',
    description: 'Simple linen clothes that provide minimal protection.',
    stackable: false,
    quantity: 1,
    value: 5,
    defense: 1,
  },
  leather_armor: {
    id: 'leather_armor',
    name: 'Leather Armor',
    type: 'ARMOR',
    description: 'Tough boiled leather cuirass offering solid defense.',
    stackable: false,
    quantity: 1,
    value: 80,
    defense: 5,
  },
  iron_armor: {
    id: 'iron_armor',
    name: 'Iron Armor',
    type: 'ARMOR',
    description: 'Heavy plate armor granting exceptional fortitude.',
    stackable: false,
    quantity: 1,
    value: 200,
    defense: 10,
  },
  healing_herb: {
    id: 'healing_herb',
    name: 'Healing Herb',
    type: 'CONSUMABLE',
    description: 'Fresh soothing forest herb. Restores 30 HP.',
    stackable: true,
    quantity: 1,
    value: 15,
    restoreHp: 30,
  },
  large_potion: {
    id: 'large_potion',
    name: 'Large Healing Potion',
    type: 'CONSUMABLE',
    description: 'A potent crimson brew. Restores 75 HP.',
    stackable: true,
    quantity: 1,
    value: 35,
    restoreHp: 75,
  },
  ashen_key: {
    id: 'ashen_key',
    name: 'Ashen Key',
    type: 'QUEST',
    description: 'An ancient obsidian key engraved with dark runes. Opens the inner chamber of the Ruined Keep.',
    stackable: false,
    quantity: 1,
    value: 0,
  },
};

export const NPCS: NPC[] = [
  {
    id: 'elder_rowan',
    name: 'Elder Rowan',
    title: 'Village Elder',
    x: 1500,
    y: 1450,
    dialogueSequence: [
      'The old keep to the northwest has awakened...',
      'Something dark is spreading through the western fields and stirring the beasts.',
      'Go east into the Whispering Forest first. Find out why the wolves have become aggressive.',
    ],
    questToOffer: 'quest_1',
    iconType: 'elder',
  },
  {
    id: 'mira_blacksmith',
    name: 'Mira',
    title: 'Blacksmith',
    x: 1370,
    y: 1490,
    dialogueSequence: [
      'Welcome to the forge! Need a sharper blade or thicker armor?',
      'The beasts out there will tear through cloth in seconds. Take a look at my wares.',
    ],
    isShop: true,
    shopInventory: ['iron_sword', 'steel_sword', 'leather_armor', 'iron_armor'],
    iconType: 'blacksmith',
  },
  {
    id: 'tomas_innkeeper',
    name: 'Tomas Falcone',
    title: 'Consigliere & Quartermaster',
    x: 1500,
    y: 1350,
    dialogueSequence: [
      'Welcome back to the Falcone Manor HQ, Underboss! The family has your back.',
      'Rest here to treat your wounds, reload your magazines, and plan our next move across the city.',
    ],
    isInn: true,
    iconType: 'innkeeper',
  },
  {
    id: 'elia_merchant',
    name: 'Elia Moretti',
    title: 'Black Market Chemist',
    x: 1630,
    y: 1490,
    dialogueSequence: [
      'Need field adrenaline or med-kits, boss? Streets are hot today.',
      'Rival hitmen carry armor-piercing slugs. Keep your health topped up at all times.',
    ],
    isShop: true,
    shopInventory: ['healing_herb', 'large_potion'],
    iconType: 'merchant',
  },
];

// Strategic Respawn Safehouses Across City Districts
export const RESPAWN_LOCATIONS: RespawnLocation[] = [
  {
    id: 'falcone_hq',
    name: 'Falcone Manor HQ',
    district: 'Little Italy Safehouse',
    x: 1500,
    y: 1585,
    description: 'The fortified headquarters and courtyard of the Falcone crime family.',
    tag: 'HQ Safehouse',
    color: '#38bdf8',
  },
  {
    id: 'moretti_hotel',
    name: 'Moretti Hotel Penthouse',
    district: 'Downtown Financial',
    x: 1450,
    y: 380,
    description: 'Luxury downtown hideout directly across from the First National Bank.',
    tag: 'High-Rise Suite',
    color: '#f59e0b',
  },
  {
    id: 'grand_royale_casino',
    name: 'Grand Royale VIP Suite',
    district: 'Chinatown Neon Strip',
    x: 2380,
    y: 320,
    description: 'High-roller VIP suite overlooking the casino strip and Chinatown alleys.',
    tag: 'Casino Penthouse',
    color: '#a855f7',
  },
  {
    id: 'harbor_pier',
    name: 'Bratva Smuggler Pier',
    district: 'Waterfront Port & Docks',
    x: 360,
    y: 1180,
    description: 'Underground dock hideout with speedboats and cargo smuggling bays.',
    tag: 'Dock Pier',
    color: '#06b6d4',
  },
  {
    id: 'chop_shop',
    name: 'Syndicate Chop Shop',
    district: 'Industrial Rail Yard',
    x: 2380,
    y: 1540,
    description: 'Reinforced mechanic garage and vehicle armor bay.',
    tag: 'Chop Shop',
    color: '#ef4444',
  },
  {
    id: 'metro_clinic',
    name: 'Riverfront Emergency Clinic',
    district: 'Grand Central Riverfront',
    x: 850,
    y: 720,
    description: 'Discreet medical facility treating gunshot wounds with no questions asked.',
    tag: 'Underground Medic',
    color: '#10b981',
  },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest_1',
    title: 'Trouble in the Forest',
    description: 'Elder Rowan asked you to investigate the Whispering Forest to the east and cull 5 aggressive wolves.',
    status: 'NOT_STARTED',
    objectives: [
      {
        id: 'cull_wolves',
        text: 'Defeat wolves in the forest',
        current: 0,
        required: 5,
        completed: false,
      },
    ],
    rewards: {
      xp: 50,
      gold: 25,
    },
  },
  {
    id: 'quest_2',
    title: 'The Abandoned Watchtower',
    description: 'Follow the Old Road north to locate the ancient watchtower and read the stone inscription.',
    status: 'NOT_STARTED',
    objectives: [
      {
        id: 'inspect_watchtower',
        text: 'Inspect the ancient inscription at the watchtower',
        current: 0,
        required: 1,
        completed: false,
      },
    ],
    rewards: {
      xp: 100,
      gold: 0,
      itemId: 'iron_sword',
    },
  },
  {
    id: 'quest_3',
    title: 'Ashen Fields',
    description: 'Cleanse the corrupted Ashen Fields to the west by destroying the dark forces.',
    status: 'NOT_STARTED',
    objectives: [
      {
        id: 'cull_skeletons',
        text: 'Defeat skeletons',
        current: 0,
        required: 5,
        completed: false,
      },
      {
        id: 'cull_cultists',
        text: 'Defeat cultists',
        current: 0,
        required: 3,
        completed: false,
      },
    ],
    rewards: {
      xp: 200,
      gold: 100,
    },
  },
  {
    id: 'quest_4',
    title: 'The Ashen Key',
    description: 'Search the ruins in the Ashen Fields for the locked chest containing the Ashen Key.',
    status: 'NOT_STARTED',
    objectives: [
      {
        id: 'obtain_ashen_key',
        text: 'Obtain the Ashen Key from the ruined shrine chest',
        current: 0,
        required: 1,
        completed: false,
      },
    ],
    rewards: {
      xp: 150,
      gold: 50,
      itemId: 'ashen_key',
    },
  },
  {
    id: 'quest_5',
    title: 'The Ruined Keep',
    description: 'Enter the Ruined Keep at the far northwest with the Ashen Key and vanquish the Ashen Lord.',
    status: 'NOT_STARTED',
    objectives: [
      {
        id: 'defeat_boss',
        text: 'Defeat the Ashen Lord in the inner sanctum',
        current: 0,
        required: 1,
        completed: false,
      },
    ],
    rewards: {
      xp: 500,
      gold: 500,
    },
  },
];

export interface BuildingBlueprint {
  type: string;
  name: string;
  category: 'Resource' | 'Power' | 'Defense' | 'Logistics' | 'Production' | 'Syndicate Front' | 'Command';
  costOre: number;
  costTitanium: number;
  costEnergyCells: number;
  costGold: number;
  powerKw: number;
  hp: number;
  description: string;
  color: string;
}

export const FACTORY_BLUEPRINTS: Record<string, BuildingBlueprint> = {
  command_hub: {
    type: 'command_hub',
    name: 'Colony Command Hub',
    category: 'Logistics',
    costOre: 40,
    costTitanium: 15,
    costEnergyCells: 5,
    costGold: 100,
    powerKw: 10,
    hp: 800,
    description: 'Central administrative nexus coordinating resource extraction and colony defense network.',
    color: '#38bdf8',
  },
  ore_extractor: {
    type: 'ore_extractor',
    name: 'Automated Ore Extractor',
    category: 'Resource',
    costOre: 15,
    costTitanium: 0,
    costEnergyCells: 2,
    costGold: 50,
    powerKw: -8,
    hp: 350,
    description: 'Drills deep into the sub-bedrock, automatically mining 1 Raw Ore every 3 seconds.',
    color: '#fb923c',
  },
  solar_generator: {
    type: 'solar_generator',
    name: 'Solar Power Array',
    category: 'Power',
    costOre: 20,
    costTitanium: 5,
    costEnergyCells: 0,
    costGold: 60,
    powerKw: 35,
    hp: 280,
    description: 'Photovoltaic solar panels generating 35 kW clean colony energy.',
    color: '#facc15',
  },
  fusion_reactor: {
    type: 'fusion_reactor',
    name: 'Helium-3 Fusion Core',
    category: 'Power',
    costOre: 50,
    costTitanium: 30,
    costEnergyCells: 15,
    costGold: 250,
    powerKw: 180,
    hp: 650,
    description: 'High-yield fusion generator providing massive 180 kW power grid coverage.',
    color: '#c084fc',
  },
  ammo_fabricator: {
    type: 'ammo_fabricator',
    name: 'Automated Munitions Press',
    category: 'Production',
    costOre: 25,
    costTitanium: 10,
    costEnergyCells: 4,
    costGold: 120,
    powerKw: -12,
    hp: 400,
    description: 'Converts raw iron ore directly into standard ballistic rounds and magazines.',
    color: '#4ade80',
  },
  defense_turret: {
    type: 'defense_turret',
    name: 'Twin-Gatling Sentry Turret',
    category: 'Defense',
    costOre: 35,
    costTitanium: 15,
    costEnergyCells: 5,
    costGold: 150,
    powerKw: -15,
    hp: 450,
    description: 'Automated dual-barrel CIWS turret with 360-degree tracking and rapid engagement.',
    color: '#ef4444',
  },
  laser_turret: {
    type: 'laser_turret',
    name: 'Heavy Pulse Laser Tower',
    category: 'Defense',
    costOre: 45,
    costTitanium: 25,
    costEnergyCells: 12,
    costGold: 220,
    powerKw: -25,
    hp: 550,
    description: 'Discharges focused thermal laser beams incinerating armored beasts and mechs.',
    color: '#a855f7',
  },
  vehicle_foundry: {
    type: 'vehicle_foundry',
    name: 'Vehicle Mech Foundry',
    category: 'Production',
    costOre: 60,
    costTitanium: 40,
    costEnergyCells: 20,
    costGold: 300,
    powerKw: -30,
    hp: 900,
    description: 'Fabricates combat buggies, heavy siege tanks, and agile exosuit mechs.',
    color: '#06b6d4',
  },
  habitat: {
    type: 'habitat',
    name: 'Pressurized Habitat Pod',
    category: 'Logistics',
    costOre: 30,
    costTitanium: 10,
    costEnergyCells: 3,
    costGold: 80,
    powerKw: -6,
    hp: 400,
    description: 'Living quarters supporting +6 colonists, technicians, and security scouts.',
    color: '#38bdf8',
  },
  bio_dome: {
    type: 'bio_dome',
    name: 'Bio-Dome Biosphere',
    category: 'Logistics',
    costOre: 35,
    costTitanium: 20,
    costEnergyCells: 5,
    costGold: 90,
    powerKw: -12,
    hp: 450,
    description: 'Pressurized biosphere dome providing oxygen, synthetic food, and housing for frontier colonists.',
    color: '#10b981',
  },
  vehicle_factory: {
    type: 'vehicle_factory',
    name: 'Vehicle Assembly Bay',
    category: 'Production',
    costOre: 50,
    costTitanium: 30,
    costEnergyCells: 15,
    costGold: 150,
    powerKw: -20,
    hp: 850,
    description: 'Industrial drydock for fabricating hover-buggies, tanks, and combat mechs.',
    color: '#38bdf8',
  },
  shield_generator: {
    type: 'shield_generator',
    name: 'Shield Generator Array',
    category: 'Defense',
    costOre: 50,
    costTitanium: 35,
    costEnergyCells: 18,
    costGold: 280,
    powerKw: -40,
    hp: 700,
    description: 'Projects a hemispherical forcefield intercepting enemy projectiles.',
    color: '#60a5fa',
  },
  shield_dome: {
    type: 'shield_dome',
    name: 'Ion Barrier Shield Dome',
    category: 'Defense',
    costOre: 50,
    costTitanium: 35,
    costEnergyCells: 18,
    costGold: 280,
    powerKw: -40,
    hp: 700,
    description: 'Projects a hemispherical forcefield intercepting enemy projectiles.',
    color: '#60a5fa',
  },
  speakeasy: {
    type: 'speakeasy',
    name: 'Front Speakeasy & Nightclub',
    category: 'Syndicate Front',
    costOre: 20,
    costTitanium: 10,
    costEnergyCells: 4,
    costGold: 120,
    powerKw: 15,
    hp: 500,
    description: 'Illicit mob club front generating passive protection racket cash ($50/min).',
    color: '#f59e0b',
  },
  casino: {
    type: 'casino',
    name: 'Underground Velvet Casino',
    category: 'Syndicate Front',
    costOre: 40,
    costTitanium: 25,
    costEnergyCells: 10,
    costGold: 280,
    powerKw: 35,
    hp: 750,
    description: 'High-stakes gambling parlor generating massive syndicate revenue ($120/min).',
    color: '#ec4899',
  },
  arms_depot: {
    type: 'arms_depot',
    name: 'Syndicate Arms Foundry',
    category: 'Production',
    costOre: 35,
    costTitanium: 20,
    costEnergyCells: 8,
    costGold: 180,
    powerKw: -15,
    hp: 600,
    description: 'Munitions foundry that continuously produces Tommy Gun drums, shotgun shells, and heavy ammo.',
    color: '#ef4444',
  },
  guard_tower: {
    type: 'guard_tower',
    name: 'Fortified Mob Guard Nest',
    category: 'Defense',
    costOre: 25,
    costTitanium: 15,
    costEnergyCells: 5,
    costGold: 140,
    powerKw: -10,
    hp: 650,
    description: 'Sandbag-reinforced bunker manned by syndicate enforcers auto-firing at rival mobsters.',
    color: '#10b981',
  },
  boat_marina: {
    type: 'boat_marina',
    name: 'River Smuggler Marina & Dock',
    category: 'Logistics',
    costOre: 30,
    costTitanium: 20,
    costEnergyCells: 6,
    costGold: 200,
    powerKw: -12,
    hp: 550,
    description: 'Deepwater dock for mooring, repairing, and spawning armed river speedboats and gunboats.',
    color: '#0284c7',
  },
  chop_shop: {
    type: 'chop_shop',
    name: 'Syndicate Chop Shop Garage',
    category: 'Production',
    costOre: 35,
    costTitanium: 25,
    costEnergyCells: 12,
    costGold: 220,
    powerKw: -18,
    hp: 800,
    description: 'Underworld auto shop modifying and repairing vintage mafia sedans and high-speed muscle cruisers.',
    color: '#8b5cf6',
  },
  safehouse_hq: {
    type: 'safehouse_hq',
    name: 'Capo Safehouse Headquarters',
    category: 'Command',
    costOre: 60,
    costTitanium: 40,
    costEnergyCells: 20,
    costGold: 450,
    powerKw: 50,
    hp: 1200,
    description: 'Fortified family command estate. Expands maximum gang troop capacity and summons elite bodyguards.',
    color: '#dc2626',
  },
};

export interface VehicleBlueprint {
  type: string;
  name: string;
  costOre: number;
  costTitanium: number;
  costEnergyCells: number;
  costGold: number;
  maxHp: number;
  armor: number;
  maxShield: number;
  maxSpeed: number;
  weaponType: 'dual_blaster' | 'heavy_cannon' | 'twin_vulcan' | 'mining_drill' | 'tommy_turret' | 'boat_cannon' | 'ram_bumper';
  color: string;
  description: string;
  isBoat?: boolean;
}

export const VEHICLE_BLUEPRINTS: Record<string, VehicleBlueprint> = {
  mafia_sedan: {
    type: 'mafia_sedan',
    name: '1930s Gangster V8 Limo',
    costOre: 25,
    costTitanium: 15,
    costEnergyCells: 5,
    costGold: 140,
    maxHp: 550,
    armor: 16,
    maxShield: 0,
    maxSpeed: 340,
    weaponType: 'tommy_turret',
    color: '#18181b',
    description: 'Classic black syndicate sedan with whitewall tires and running boards for Tommy gun drive-bys.',
  },
  muscle_car: {
    type: 'muscle_car',
    name: 'Stallion 427 V8 Muscle',
    costOre: 30,
    costTitanium: 20,
    costEnergyCells: 6,
    costGold: 220,
    maxHp: 480,
    armor: 14,
    maxShield: 0,
    maxSpeed: 420,
    weaponType: 'ram_bumper',
    color: '#dc2626',
    description: 'Raw American muscle coupe with tire-smoking burnout torque and reinforced ram bumper.',
  },
  armored_van: {
    type: 'armored_van',
    name: 'Bank Enforcer Armored Truck',
    costOre: 55,
    costTitanium: 35,
    costEnergyCells: 10,
    costGold: 320,
    maxHp: 950,
    armor: 28,
    maxShield: 100,
    maxSpeed: 240,
    weaponType: 'tommy_turret',
    color: '#334155',
    description: 'Heavy bulletproof armored transport built to withstand rocket attacks and ram roadblocks.',
  },
  sports_coupe: {
    type: 'sports_coupe',
    name: 'Viper GT Syndicate Roadster',
    costOre: 28,
    costTitanium: 18,
    costEnergyCells: 8,
    costGold: 260,
    maxHp: 380,
    armor: 10,
    maxShield: 0,
    maxSpeed: 450,
    weaponType: 'dual_blaster',
    color: '#f59e0b',
    description: 'Ultra-fast luxury roadster designed for swift police escapes and lightning hit-and-runs.',
  },
  river_speedboat: {
    type: 'river_speedboat',
    name: 'Cigarette Syndicate Speedboat',
    costOre: 30,
    costTitanium: 18,
    costEnergyCells: 8,
    costGold: 200,
    maxHp: 420,
    armor: 12,
    maxShield: 0,
    maxSpeed: 390,
    weaponType: 'dual_blaster',
    color: '#0284c7',
    description: 'Twin-engine high-performance river boat cutting through water channels with churning wake.',
    isBoat: true,
  },
  patrol_gunboat: {
    type: 'patrol_gunboat',
    name: 'Armored River Patrol Gunboat',
    costOre: 50,
    costTitanium: 35,
    costEnergyCells: 14,
    costGold: 360,
    maxHp: 750,
    armor: 22,
    maxShield: 150,
    maxSpeed: 290,
    weaponType: 'boat_cannon',
    color: '#0f766e',
    description: 'Heavy naval patrol boat with forward 75mm concussive cannon for dominating river traffic.',
    isBoat: true,
  },
  scout_buggy: {
    type: 'scout_buggy',
    name: 'Viper Scout Hover-Buggy',
    costOre: 30,
    costTitanium: 15,
    costEnergyCells: 6,
    costGold: 150,
    maxHp: 320,
    armor: 8,
    maxShield: 100,
    maxSpeed: 380,
    weaponType: 'dual_blaster',
    color: '#38bdf8',
    description: 'High-speed hover vehicle with twin energy repeaters and agile drifting.',
  },
  siege_tank: {
    type: 'siege_tank',
    name: 'Goliath 120mm Siege Tank',
    costOre: 70,
    costTitanium: 45,
    costEnergyCells: 15,
    costGold: 350,
    maxHp: 800,
    armor: 22,
    maxShield: 200,
    maxSpeed: 190,
    weaponType: 'heavy_cannon',
    color: '#f97316',
    description: 'Heavy tracked armored fortress firing 120mm high-explosive concussive shells.',
  },
  mech_walker: {
    type: 'mech_walker',
    name: 'Titan Bipedal Combat Mech',
    costOre: 60,
    costTitanium: 40,
    costEnergyCells: 20,
    costGold: 400,
    maxHp: 650,
    armor: 16,
    maxShield: 250,
    maxSpeed: 230,
    weaponType: 'twin_vulcan',
    color: '#a855f7',
    description: 'Bipedal walking mech armed with twin rotary vulcans and armored chassis.',
  },
  harvester: {
    type: 'harvester',
    name: 'Scarab Mineral Harvester',
    costOre: 40,
    costTitanium: 20,
    costEnergyCells: 10,
    costGold: 200,
    maxHp: 480,
    armor: 14,
    maxShield: 120,
    maxSpeed: 260,
    weaponType: 'mining_drill',
    color: '#eab308',
    description: 'Heavy industrial rover equipped with ultrasonic mining drills to harvest nodes rapidly.',
  },
};

export const INITIAL_TURF_DISTRICTS = [
  {
    id: 'district_little_italy',
    name: 'Little Italy & Falcone Strip',
    x: 950,
    y: 1100,
    w: 1050,
    h: 880,
    controllingFaction: 'player_syndicate' as const,
    playerControlPercent: 95,
    incomePerMin: 150,
    color: '#dc2626',
    description: 'Heart of the Falcone family operations. Ristorantes, social clubs, and loyal capos.',
  },
  {
    id: 'district_downtown',
    name: 'Downtown Financial & City Bank',
    x: 950,
    y: 50,
    w: 1050,
    h: 780,
    controllingFaction: 'moretti_mob' as const,
    playerControlPercent: 20,
    incomePerMin: 280,
    color: '#3b82f6',
    description: 'Skyscrapers, First National City Bank, and luxury hotel plazas contested by the Moretti Syndicate.',
  },
  {
    id: 'district_waterfront',
    name: 'Waterfront Docks & Smuggler Port',
    x: 0,
    y: 1100,
    w: 950,
    h: 880,
    controllingFaction: 'bratva_cartel' as const,
    playerControlPercent: 15,
    incomePerMin: 210,
    color: '#10b981',
    description: 'River piers, shipping container yards, and contraband warehouses held by Bratva soldiers.',
  },
  {
    id: 'district_neon_casino',
    name: 'Neon Strip & Chinatown Quarter',
    x: 2000,
    y: 50,
    w: 1000,
    h: 780,
    controllingFaction: 'yakuza_clan' as const,
    playerControlPercent: 25,
    incomePerMin: 340,
    color: '#a855f7',
    description: 'The Grand Royale Casino, neon marquees, and gambling dens ruled by the Yakuza clan.',
  },
  {
    id: 'district_industrial',
    name: 'Industrial Chop Shop & Rail Yard',
    x: 2000,
    y: 1100,
    w: 1000,
    h: 880,
    controllingFaction: 'player_syndicate' as const,
    playerControlPercent: 45,
    incomePerMin: 180,
    color: '#f59e0b',
    description: 'Steel foundries, rail depots, and chop shop garages churning out armed getaway vehicles.',
  },
];

